import { Bell, MessageSquare, FileText, Zap, Star, Check } from 'lucide-react';
import type { AppNotification } from '@/types/notification';

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: '1',
    type: 'ai',
    icon: Zap,
    iconBg: 'bg-[rgba(233,162,76,0.12)]',
    iconColor: 'text-[#E9A24C]',
    title: 'New AI Model Available',
    desc: 'GPT-4o Vision is now available in your workspace. Try analyzing images in chat.',
    time: '5 minutes ago',
    unread: true,
    action: 'Try now',
  },
  {
    id: '2',
    type: 'chat',
    icon: MessageSquare,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-500',
    title: 'Chat export ready',
    desc: 'Your "Market Research" conversation has been exported as PDF (2.3 MB).',
    time: '1 hour ago',
    unread: true,
    action: 'Download',
  },
  {
    id: '3',
    type: 'doc',
    icon: FileText,
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-500',
    title: 'Document analyzed',
    desc: 'AI has finished analyzing "Q3 Financial Report.xlsx". 12 key insights found.',
    time: '3 hours ago',
    unread: true,
    action: 'View insights',
  },
  {
    id: '4',
    type: 'team',
    icon: Star,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-500',
    title: 'Workspace shared',
    desc: 'Sarah Chen invited you to the "Design System 2025" workspace.',
    time: '1 day ago',
    unread: false,
    action: 'Accept',
  },
  {
    id: '5',
    type: 'system',
    icon: Bell,
    iconBg: 'bg-[rgba(0,0,0,0.04)]',
    iconColor: 'text-[#999]',
    title: 'Weekly summary ready',
    desc: 'Your AI productivity report for Dec 16–22 is ready to view.',
    time: '2 days ago',
    unread: false,
    action: 'View report',
  },
  {
    id: '6',
    type: 'billing',
    icon: Check,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-500',
    title: 'Payment successful',
    desc: '$19.00 charged for your Pro plan. Receipt sent to alex@company.com.',
    time: '5 days ago',
    unread: false,
    action: 'View receipt',
  },
];
