import { AlertTriangle, Bell, Check, CreditCard, FileText, MessageSquare, Shield, Sparkles, Star, Users, Zap } from 'lucide-react';
import type { AppNotification } from '@/types/notification';

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: '1',
    type: 'ai',
    category: 'AI Updates',
    priority: 'high',
    icon: Zap,
    iconBg: 'bg-[rgba(233,162,76,0.12)]',
    iconColor: 'text-[#E9A24C]',
    title: 'New AI Model Available',
    desc: 'GPT-4o Vision is now available in your workspace. Try analyzing images in chat.',
    time: '5 minutes ago',
    unread: true,
    action: 'Try now',
  },
  {
    id: '2',
    type: 'chat',
    category: 'Chats',
    priority: 'medium',
    icon: MessageSquare,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-500',
    title: 'Chat export ready',
    desc: 'Your Market Research conversation has been exported as PDF and is ready to download.',
    time: '1 hour ago',
    unread: true,
    action: 'Download',
  },
  {
    id: '3',
    type: 'doc',
    category: 'Documents',
    priority: 'high',
    icon: FileText,
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-500',
    title: 'Document analyzed',
    desc: 'AI has finished analyzing Q3 Financial Report.xlsx. 12 key insights were found.',
    time: '3 hours ago',
    unread: true,
    action: 'View insights',
  },
  {
    id: '4',
    type: 'team',
    category: 'Workspace',
    priority: 'medium',
    icon: Users,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-500',
    title: 'Workspace shared',
    desc: 'Sarah Chen invited you to collaborate in the Design System 2025 workspace.',
    time: '1 day ago',
    unread: false,
    action: 'Accept',
  },
  {
    id: '5',
    type: 'system',
    category: 'System',
    priority: 'low',
    icon: Bell,
    iconBg: 'bg-[rgba(0,0,0,0.04)]',
    iconColor: 'text-[#999]',
    title: 'Weekly summary ready',
    desc: 'Your AI productivity report for Dec 16–22 is ready to view.',
    time: '2 days ago',
    unread: false,
    action: 'View report',
  },
  {
    id: '6',
    type: 'billing',
    category: 'Billing',
    priority: 'low',
    icon: CreditCard,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-500',
    title: 'Payment successful',
    desc: '$19.00 charged for your Pro plan. Receipt sent to alex@company.com.',
    time: '5 days ago',
    unread: false,
    action: 'View receipt',
  },
  {
    id: '7',
    type: 'system',
    category: 'Security',
    priority: 'high',
    icon: Shield,
    iconBg: 'bg-red-50',
    iconColor: 'text-red-500',
    title: 'New device signed in',
    desc: 'A new Chrome session was created from San Francisco, CA. Review it if this was not you.',
    time: '6 days ago',
    unread: true,
    action: 'Review',
  },
  {
    id: '8',
    type: 'ai',
    category: 'AI Usage',
    priority: 'medium',
    icon: Sparkles,
    iconBg: 'bg-[rgba(233,162,76,0.12)]',
    iconColor: 'text-[#E9A24C]',
    title: 'Usage milestone reached',
    desc: 'You saved an estimated 40 hours this month using AI-powered document workflows.',
    time: '1 week ago',
    unread: false,
    action: 'Open analytics',
  },
  {
    id: '9',
    type: 'team',
    category: 'Mentions',
    priority: 'medium',
    icon: Star,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-500',
    title: 'You were mentioned',
    desc: 'Noah mentioned you in Engineering Architecture while reviewing the API summary.',
    time: '1 week ago',
    unread: false,
    action: 'View mention',
  },
  {
    id: '10',
    type: 'billing',
    category: 'Billing',
    priority: 'high',
    icon: AlertTriangle,
    iconBg: 'bg-red-50',
    iconColor: 'text-red-500',
    title: 'Storage limit warning',
    desc: 'Your document storage is at 84%. Upgrade or remove unused files to avoid upload limits.',
    time: '2 weeks ago',
    unread: false,
    action: 'Manage plan',
  },
  {
    id: '11',
    type: 'system',
    category: 'System',
    priority: 'low',
    icon: Check,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-500',
    title: 'Backup completed',
    desc: 'Your workspace knowledge base was backed up successfully.',
    time: '2 weeks ago',
    unread: false,
    action: 'Details',
  },
];
