export const queryKeys = {
  currentUser: ['current-user'] as const,
  notifications: ['notifications'] as const,
  conversations: ['conversations'] as const,
  activeConversation: ['active-conversation'] as const,
  chatMessages: ['chat-messages'] as const,
  chatHistory: ['chat-history'] as const,
  recentChats: ['recent-chats'] as const,
  dashboard: ['dashboard'] as const,
  documents: ['documents'] as const,
  workspace: ['workspace'] as const,
  analytics: ['analytics'] as const,
  profile: ['profile'] as const,
  settings: ['settings'] as const,
  billing: ['billing'] as const,
} as const;
