export const queryKeys = {
  currentUser: ['current-user'] as const,
  notifications: ['notifications'] as const,
  conversations: ['conversations'] as const,
  activeConversation: ['active-conversation'] as const,
  chatMessages: ['chat-messages'] as const,
  chatHistory: ['chat-history'] as const,
  recentChats: ['recent-chats'] as const,
  dashboard: ['dashboard'] as const,
  documents: ['documents'] as const,
  workspace: ['workspace'] as const,
  analytics: ['analytics'] as const,
  profile: ['profile'] as const,
  settings: ['settings'] as const,
  billing: ['billing'] as const,
  search: ['global-search'] as const,
  recentSearches: ['recent-searches'] as const,
  api: {
    health: ['api', 'health'] as const,
    authUser: ['api', 'auth', 'user'] as const,
    dashboard: ['api', 'dashboard'] as const,
    conversations: ['api', 'conversations'] as const,
    conversation: (conversationId: string) => ['api', 'conversations', conversationId] as const,
    conversationMessages: (conversationId: string) => ['api', 'conversations', conversationId, 'messages'] as const,
    documents: ['api', 'documents'] as const,
    document: (documentId: string) => ['api', 'documents', documentId] as const,
    notifications: ['api', 'notifications'] as const,
    search: ['api', 'search'] as const,
    analytics: ['api', 'analytics'] as const,
    workspace: ['api', 'workspace'] as const,
    settings: ['api', 'settings'] as const,
    billing: ['api', 'billing'] as const,
  },
} as const;
