export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY: '/verify',
  SSO_CALLBACK: '/sso-callback',
  DASHBOARD: '/dashboard',
} as const;

export const DASHBOARD_SEGMENTS = {
  CHAT: 'chat',
  DOCUMENTS: 'documents',
  ANALYTICS: 'analytics',
  WORKSPACE: 'workspace',
  MODELS: 'models',
  NOTIFICATIONS: 'notifications',
  SETTINGS: 'settings',
  BILLING: 'billing',
  PROFILE: 'profile',
  TEAM: 'team',
  ADMIN: 'admin',
} as const;

export const DASHBOARD_PATHS = {
  ROOT: ROUTES.DASHBOARD,
  CHAT: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.CHAT}`,
  DOCUMENTS: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.DOCUMENTS}`,
  ANALYTICS: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.ANALYTICS}`,
  WORKSPACE: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.WORKSPACE}`,
  MODELS: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.MODELS}`,
  NOTIFICATIONS: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.NOTIFICATIONS}`,
  SETTINGS: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.SETTINGS}`,
  BILLING: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.BILLING}`,
  PROFILE: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.PROFILE}`,
  TEAM: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.TEAM}`,
  ADMIN: `${ROUTES.DASHBOARD}/${DASHBOARD_SEGMENTS.ADMIN}`,
} as const;

export const AUTH_ROUTES = [
  ROUTES.LOGIN,
  ROUTES.SIGNUP,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.RESET_PASSWORD,
  ROUTES.VERIFY,
  ROUTES.SSO_CALLBACK,
] as const;
