export const API_ENDPOINTS = {
  health: '/health',
  auth: {
    me: '/auth/me',
    session: '/auth/session',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  users: {
    current: '/users/me',
    profile: '/users/me/profile',
    avatar: '/users/me/avatar',
    settings: '/users/me/settings',
  },
  conversations: {
    root: '/conversations',
    byId: (conversationId: string) => `/conversations/${conversationId}`,
    rename: (conversationId: string) => `/conversations/${conversationId}/rename`,
    pin: (conversationId: string) => `/conversations/${conversationId}/pin`,
    favorite: (conversationId: string) => `/conversations/${conversationId}/favorite`,
    messages: (conversationId: string) => `/conversations/${conversationId}/messages`,
    message: (conversationId: string, messageId: string) => `/conversations/${conversationId}/messages/${messageId}`,
    reaction: (conversationId: string, messageId: string) => `/conversations/${conversationId}/messages/${messageId}/reaction`,
    regenerate: (conversationId: string, messageId: string) => `/conversations/${conversationId}/messages/${messageId}/regenerate`,
  },
  documents: {
    root: '/documents',
    upload: '/documents/upload',
    recent: '/documents/recent',
    categories: '/documents/categories',
    tags: '/documents/tags',
    byId: (documentId: string) => `/documents/${documentId}`,
    preview: (documentId: string) => `/documents/${documentId}/preview`,
    analyze: (documentId: string) => `/documents/${documentId}/analyze`,
  },
  workspace: {
    root: '/workspace',
    summary: '/workspace/summary',
    members: '/workspace/members',
    activity: '/workspace/activity',
  },
  analytics: {
    overview: '/analytics/overview',
    usage: '/analytics/usage',
    tokens: '/analytics/tokens',
    workspaces: '/analytics/workspaces',
  },
  notifications: {
    root: '/notifications',
    byId: (notificationId: string) => `/notifications/${notificationId}`,
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    markAllRead: '/notifications/read-all',
    clearAll: '/notifications/clear',
  },
  settings: {
    root: '/settings',
    section: (section: string) => `/settings/${section}`,
  },
  billing: {
    plans: '/billing/plans',
    subscription: '/billing/subscription',
    invoices: '/billing/invoices',
    paymentMethods: '/billing/payment-methods',
  },
} as const;
